language: node_js
node_js:
  - lts/*

services:
  - docker

before_script:
  - docker build --network=host -t dogecoind provision/dogecoind/

script:
  - npm run lint
  - npm test

before_deploy:
  - npm pack

deploy:
  provider: releases
  api_key: $GH_TOKEN  
  file: dogecoin-spv-${TRAVIS_TAG/v}.tgz
  skip_cleanup: true
  on:
    tags: true
