language: node_js
node_js:
  - "16"

services:
  - docker

before_script:
  - docker build --no-cache -t dogecoind provision/dogecoind/

script:
  - npm run lint
  - npm test

before_deploy:
  - npm -g install pkg
  - make package

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: 
    - dogecoin-spv-${TRAVIS_TAG/v}-linux-x64.tar.gz
    - dogecoin-spv-${TRAVIS_TAG/v}-win-x64.zip
    - dogecoin-spv-${TRAVIS_TAG/v}-darwin-x64.zip 
  skip_cleanup: true
  on:
    tags: true
